#!/usr/bin/env bash
set -xo pipefail nounset

if [[ "${TRACE-0}" == "1" ]]; then
    set -o xtrace
fi
cd "$(dirname "$0")"

playerctl -p cmus,%any play
if test "$(playerctl -p cmus,%any status)" != "Playing"; then
    notify-send "🍅 ⚠️" "Couldn’t start playing anything"
fi
playerctl -p cmus,%any loop Playlist

notify-send --wait -A "pomodoro cancel=Cancel" -A "pomodoro finish=Finish" "$(pomodoro status --format "🍅 %c: Started")" "$(pomodoro status --format "%d")"

if test -f ~/.bin/dnd_toggle && test -x ~/.bin/dnd_toggle ; then
    ~/.bin/dnd_toggle on
else
    ps -C mako >/dev/null
    if [[ $? -eq 0 ]]; then
        makoctl set-mode do-not-disturb
    fi
    dunst_pid=$(pgrep dunst)
    if [[ $? -eq 0 ]]; then
        kill -SIGUSR1 "$dunst_pid"
    fi
fi
