#!/usr/bin/env bash
set -xo pipefail nounset

if [[ "${TRACE-0}" == "1" ]]; then
    set -o xtrace
fi
cd "$(dirname "$0")"

notify-send -u critical "$(pomodoro status --format "🍅 %c ended")" "$(pomodoro status --format "%d")"

if test -f ~/.bin/dnd_toggle && test -x ~/.bin/dnd_toggle ; then
    ~/.bin/dnd_toggle off
else
    ps -C mako >/dev/null
    if [[ $? -eq 0 ]]; then
        makoctl set-mode normal
    fi
    dunst_pid=$(pgrep dunst)
    if [[ $? -eq 0 ]]; then
        kill -SIGUSR2 "$dunst_pid"
    fi
fi

playerctl -p cmus,%any pause
