#!/usr/bin/env bash
set -xo pipefail

notify-send -u critical "$(pomodoro status --format "🍅 %c ended")" "$(pomodoro status --format "%d")"

ps -C mako >/dev/null
if [[ $? -eq 0 ]]; then
    makoctl set-mode normal
fi
dunst_pid=$(pgrep dunst)
if [[ $? -eq 0 ]]; then
    kill -SIGUSR2 $dunst_pid
fi

cmus-remote -s || echo "Error with cmus"
